foreground         #F6F8FA
background         #090C0F
cursor             #ADB3B8

active_tab_foreground     #090C0F
active_tab_background     #F6F8FA
inactive_tab_foreground   #F6F8FA
inactive_tab_background   #090C0F

active_border_color   #435564
inactive_border_color #090C0F
bell_border_color     #ABB1B6
