directory: ~/music
library: ~/.config/beets/library.db

pluginpath:
  - ~/.config/beets/plugins

plugins: chroma fetchart embedart musicbrainz singletoncoverart

import:
  move: yes
  write: yes
  incremental: yes

fetchart:
  auto: yes
  sources: coverart
  cautious: yes

embedart:
  auto: yes

chroma:
  auto: yes

acoustid:
  apikey: RFgKEdTDpF

singletoncoverart:
  ifempty: yes
  max_releases: 8
  image_size: 500
  request_timeout: 15

paths:
  default: $albumartist/$title
  singleton: $artist/$title
