# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(090C0F)
$foreground = rgb(F6F8FA)
$color0 = rgb(46484A)
$color1 = rgb(ABB1B6)
$color2 = rgb(7B8287)
$color3 = rgb(6A7F8E)
$color4 = rgb(435564)
$color5 = rgb(4C5358)
$color6 = rgb(1C242A)
$color7 = rgb(E9EDF0)
$color8 = rgb(A3A6A8)
$color9 = rgb(E4ECF2)
$color10 = rgb(A5ADB4)
$color11 = rgb(8DA9BD)
$color12 = rgb(597185)
$color13 = rgb(656E76)
$color14 = rgb(263037)
$color15 = rgb(E9EDF0)
